#!/bin/bash

OIFS="$IFS"
IFS=$'\n'
curd=`pwd`

# find all java files including subfolders then compile
for A in `find . -iname "*.java"`
do 
   if echo `dirname $A` |grep -qwi "Trash"; then
      continue
   fi
   pathA=`dirname $A`
   pathA=$curd${pathA#.}
   cd $pathA
   javac -d . $pathA/$(basename $A)
   
   # find all java classes including subfolders then run
   for B in `find . -iname "*.class"`
   do
      scurd=`pwd`
      if [ $(basename $B .class) == $(basename $A .java) ]; then
         if [ $(dirname $B) == $(dirname $A) ]; then 
             java `basename $B .class`
             break
         else
             pathB=`dirname $B`
             pathB=$scurd${pathB#.}
             packname=`echo ${pathB##$pathA/} |sed 's/\//./g'`
             if grep -qwi ${packname} $(basename $A); then
                java $packname.$(basename $B .class)
                break
             fi   
	 fi
      fi
   done
done
IFS="$OIFS"
